### ISSUE TITLE
Injected stylesheet 'scroll-behaviour: smooth;' breaks sites using Lenis smooth scroll

### ISSUE THREAD

**Issue by tobimori** [ffoodd/a11y.css-webextension#129]
I noticed this extension injects a CSS declaration that sets `scroll-behaviour: smooth;`. This makes all sites using Lenis impossible to use (because it requires `scroll-behaviour: auto`).  Why so?
I do not expect this addon to alter behaviour on any site by default or make them unusable..

**Comment by ffoodd** [comment]
FWIW, it's been handled [in Lenis](https://github.com/darkroomengineering/lenis/issues/344) and makes sense.

As far as I understand, they've been recommending to set `.lenis.lenis-smooth {  scroll-behavior: auto !important; }` for quite some time, already.
