### ISSUE TITLE
:target styles mess up page styles

### ISSUE THREAD

**Issue by robinmetral** [ffoodd/a11y.css-webextension#42]
The extension's `:target` styles:

https://github.com/ffoodd/a11y.css-webextension/blob/cb1a243de82e8654ed857d0855b2928c3bbd4f29/scripts/injected/alt.css#L134-L137

...effectively apply `display: block;` to all targets. This can be an issue, for example:

```html
<p>
  This is some paragraph with a link to a footnote.<sup><a href="footnote-1" id="footnote-1-ref">1</a></sup>
</p>
<ol>
  <li id="#footnote-1">This is the footnote! <a href="footnote-1-ref">Back to content</a></li>
</ol>
```

In this case, applying `display: block;` will:

- override the implicit `display: list-item;` of the footnote, so the list item will lose its marker (and order in the list)
- override the implicit `display: inline;` of the footnote ref, so when going back to the content, the footnote ref will be on its own line

**Comment by ffoodd** [comment]
Hi there, thanks for reporting this issue!

May I know which browser you're using, and whether it's applied by default or after opening extension popup?

I'm adjusting styles to mitigate this but would love to be able to reproduce the behavior to ensure the fix is working.

**Comment by ffoodd** [comment]
I'm really confident with my fix, so you may expect this issue to be fixed in the next release :)

**Comment by robinmetral** [comment]
Thanks for the quick fix! :tada: 

For what it's worth I'm on Firefox, and this was applied by default.

Let me know if you'd like me to verify the fix after the release!
